### ISSUE TITLE
muffin watch -s errors execvp(): No such file or directory

### ISSUE THREAD

**Issue by thunderrabbit** [Axonify/muffin.io#3]
I see an [answer on SO](http://stackoverflow.com/questions/21992657/node-js-spawned-process-is-generating-error-execvp-no-such-file-or-directo), but not sure if/how I can apply it.

Here's the console output.
http://pastebin.com/2BU96FPT

Running on OS X Mavericks.

Is there a log somewhere?

**Comment by ylian** [comment]
It seems that you haven’t installed Google App Engine for Python, or not properly. Install GAE for Python here: https://developers.google.com/appengine/downloads#Google_App_Engine_SDK_for_Python

Or are you using Windows? I only tested on Mac.

Yaogang

**Comment by thunderrabbit** [comment]
Interesting.  Yes; that solved it.  I had installed GAE for Python already, but the GAE launcher had recently popped itself up for an update, and I hadn't clicked OK to authorize it.  Once I did that, everything worked fine.  Thanks!!

**Comment by ylian** [comment]
Yes. Google App Engine Launcher requires you to recreate symlinks every time you update it.
BTW, you can also use GAE launcher to run the server, and use `muffin watch` for just the client code. It's easier to see the GAE logs this way.
