### ISSUE TITLE
Can't build muffin

### ISSUE THREAD

**Issue by jsvazic** [Axonify/muffin.io#4]
Hey Yaogang,

I'm trying to re-install the new version that you patched for me but now I'm getting the following:

```
john@John-ThinkPad-X1-Carbon:~/source/muffin.io$ npm install
npm WARN package.json muffin.io@0.1.5a No repository field.
npm WARN package.json ansi-color@0.2.1 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json docco@0.3.0 No repository field.
npm WARN package.json growl@1.5.1 No repository field.
npm WARN package.json uglify-js@2.2.5 'repositories' (plural) Not supported. Please pick one as the 'repository' field
john@John-ThinkPad-X1-Carbon:~/source/muffin.io$ 
```

Any ideas?

**Comment by axnd** [comment]
Those are just warnings corresponding to the `package.json` entries for some of the dependencies, it should still have built.

**Comment by ylian** [comment]
Those are just warnings. You have already installed muffin in that folder. That's why the installation stops there.

Please install muffin as a global package.

```
sudo npm install -g
```

**Comment by jsvazic** [comment]
Thanks guys, those worked.
