### ISSUE TITLE
Couldn't open muffin.io

### ISSUE THREAD

**Issue by syhily** [Axonify/muffin.io#7]

**Comment by ylian** [comment]
I'm no longer maintaining muffin. The muffin.io website is also no longer registered.

**Comment by syhily** [comment]
I would be appreciate if you could share the source of muffin.io document site.

**Comment by ylian** [comment]
[muffin-website-master.zip](https://github.com/Axonify/muffin.io/files/519145/muffin-website-master.zip)

**Comment by syhily** [comment]
`[ERROR]: Failed to load plugin muffin-compiler-jade.`
